version: "3"
services:
  worker:
    container_name: hs
    build:
      context: .
      args:
        REFRESH_RATE: ${REFRESH_RATE}
    env_file:
      - .env
    volumes:
      - ./filter.yaml:/app/filter.yaml
      - ./source.yaml:/app/source.yaml
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example_password
      - POSTGRES_USER=example
      - POSTGRES_DB=example
